In [2]:
import pandas as pd
import numpy as np

In [5]:
customers=pd.read_csv(r"d:\End to End Project\Ecommerce_Analysis\customers.csv",)

In [3]:
customers.head()

  customer_id customer_name  gender  age       city          state signup_date
0       C0001    Customer 1    Male   38    Kolkata  Uttar Pradesh  2023-08-05
1       C0002    Customer 2  Female   49    Chennai        Gujarat  2023-11-02
2       C0003    Customer 3    Male   40  Ahmedabad        Gujarat  2025-03-07
3       C0004    Customer 4    Male   50    Kolkata    West Bengal  2023-07-04
4       C0005    Customer 5    Male   20    Lucknow          Delhi  2023-02-08

In [4]:
customers.shape

(500, 7)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    500 non-null    str
 1   customer_name  500 non-null    str
 2   gender         500 non-null    str
 3   age            500 non-null    int64
 4   city           499 non-null    str
 5   state          499 non-null    str
 6   signup_date    500 non-null    str
dtypes: int64(1), str(6)
memory usage: 27.5 KB

In [6]:
customers.isna().sum()

customer_id      0
customer_name    0
gender           0
age              0
city             1
state            1
signup_date      0
dtype: int64

In [7]:
customers.describe()

              age
count  500.000000
mean    38.878000
std     12.071726
min     18.000000
25%     29.000000
50%     40.000000
75%     49.000000
max     60.000000

In [8]:
customers.duplicated().sum()

np.int64(0)

gender column mein Male aur Female kitne customers hain?

In [9]:
customers['gender'].value_counts()

gender
Female    256
Male      244
Name: count, dtype: int64

Customers ki average age kya hai?

In [10]:
customers['age'].mean()

np.float64(38.878)

Kaunsa city sabse zyada customers rakhta hai?

In [11]:
customers['city'].value_counts()

city
Delhi        57
Jaipur       56
Pune         55
Chennai      53
Bengaluru    50
Kolkata      47
Ahmedabad    46
Hyderabad    46
Lucknow      45
Mumbai       44
Name: count, dtype: int64

Customers ka signup year-wise count nikalo.

In [12]:
customers['signup_date']=pd.to_datetime(customers['signup_date'])

In [13]:
products=pd.read_csv(r'd:\End to End Project\chatgpt  ecommerce\products.csv')

In [14]:
products.head()

,product_id,product_name,category,sub_category,price,cost
0,P001,Wireless Mouse,Electronics,Accessories,799,528.51
1,P002,Mechanical Keyboard,Electronics,Computer Accessories,3499,2531.45
2,P003,USB-C Hub,Electronics,Computer Accessories,1299,899.54
3,P004,Laptop Stand,Accessories,Office,1899,1174.33
4,P005,Bluetooth Speaker,Electronics,Audio,2499,1621.79

In [15]:
products.shape

(16, 6)

In [16]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    16 non-null     str
 1   product_name  16 non-null     str
 2   category      16 non-null     str
 3   sub_category  16 non-null     str
 4   price         16 non-null     int64
 5   cost          16 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 900.0 bytes

In [17]:
products.isnull().sum()

product_id      0
product_name    0
category        0
sub_category    0
price           0
cost            0
dtype: int64

In [18]:
products.duplicated().sum()

np.int64(0)

In [19]:
products.describe()

              price          cost
count     16.000000     16.000000
mean    4480.250000   2895.824375
std     4250.681318   2835.982283
min      799.000000    528.510000
25%     1574.000000   1086.475000
50%     2649.000000   1666.045000
75%     6249.000000   3606.295000
max    14999.000000  10433.810000

Kaunsi category mein sabse zyada products hain?

In [20]:
products['category'].value_counts()

category
Electronics    10
Accessories     4
Wearables       1
Furniture       1
Name: count, dtype: int64

Products ka average price aur average cost kya hai?

In [21]:
products[['price','cost']].mean()

price    4480.250000
cost     2895.824375
dtype: float64

In [22]:
orders=pd.read_csv(r'd:\End to End Project\chatgpt  ecommerce\orders.csv')

In [23]:
orders.head()

,order_id,customer_id,order_date,product_id,quantity,discount,payment_method,region
0,O00001,C0019,2025-08-09,P004,2,0.15,UPI,South
1,O00002,C0365,2025-11-04,P002,1,0.20,Cash on Delivery,West
2,O00003,C0300,2025-05-04,P015,2,0.10,Debit Card,East
3,O00004,C0007,2025-08-19,P004,5,0.25,UPI,East
4,O00005,C0249,2025-06-27,P006,3,0.20,Debit Card,West

In [24]:
orders.shape

(5000, 8)

In [25]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5000 non-null   str
 1   customer_id     5000 non-null   str
 2   order_date      5000 non-null   str
 3   product_id      5000 non-null   str
 4   quantity        5000 non-null   int64
 5   discount        4999 non-null   float64
 6   payment_method  5000 non-null   str
 7   region          5000 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 312.6 KB

In [26]:
orders.isnull().sum()

order_id          0
customer_id       0
order_date        0
product_id        0
quantity          0
discount          1
payment_method    0
region            0
dtype: int64

In [27]:
orders.duplicated().sum()

np.int64(0)

In [28]:
orders.describe()

          quantity     discount
count  5000.000000  4999.000000
mean      2.398200     0.123355
std       1.406994     0.086158
min       1.000000     0.000000
25%       1.000000     0.050000
50%       2.000000     0.100000
75%       4.000000     0.200000
max       5.000000     0.250000

quantity ka minimum, maximum aur average kya hai?

In [29]:
orders['quantity'].describe()

count    5000.000000
mean        2.398200
std         1.406994
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         5.000000
Name: quantity, dtype: float64

Kaunsa payment method sabse zyada use hua?

In [30]:
orders['payment_method'].value_counts()

payment_method
Cash on Delivery    1044
Debit Card          1003
Net Banking         1001
Credit Card          995
UPI                  956
upi                    1
Name: count, dtype: int64

Orders ka monthly trend nikalo.

In [31]:
orders['order_date']=pd.to_datetime(orders['order_date'])

In [32]:
orders["order_date"].dt.month.value_counts().sort_index()

order_date
1     425
2     376
3     433
4     439
5     431
6     405
7     447
8     411
9     404
10    391
11    405
12    433
Name: count, dtype: int64

In [33]:
returns=pd.read_csv(r'd:\End to End Project\chatgpt  ecommerce\returns.csv')

In [34]:
returns.head()

  return_id order_id return_date    return_reason
0     R0001   O03595  2025-02-02    Wrong Product
1     R0002   O03028  2025-08-28    Wrong Product
2     R0003   O00878  2025-10-28  Product Quality
3     R0004   O04991  2025-01-21  Product Quality
4     R0005   O03522  2025-12-20    Late Delivery

In [35]:
returns.shape

(400, 4)

In [36]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      400 non-null    str
 1   order_id       400 non-null    str
 2   return_date    400 non-null    str
 3   return_reason  400 non-null    str
dtypes: str(4)
memory usage: 12.6 KB

In [37]:
returns.isna().sum()

return_id        0
order_id         0
return_date      0
return_reason    0
dtype: int64

In [38]:
returns.duplicated().sum()

np.int64(0)

In [39]:
returns.describe()

       return_id order_id return_date  return_reason
count        400      400         400            400
unique       400      400         238              5
top        R0001   O03595  2025-03-26  Wrong Product
freq           1        1           7             90

Sabse common return reason kya hai?

In [40]:
returns['return_reason'].value_counts()

return_reason
Wrong Product      90
Changed Mind       86
Late Delivery      80
Damaged            76
Product Quality    68
Name: count, dtype: int64

Kya returns["order_id"] mein duplicate order IDs hain?

In [41]:
returns['order_id'].duplicated().sum()

np.int64(0)

Total unique returned orders kitne hain?

In [42]:
returns['order_id'].nunique()

400

In [43]:
customers.head()

  customer_id customer_name  gender  age       city          state signup_date
0       C0001    Customer 1    Male   38    Kolkata  Uttar Pradesh  2023-08-05
1       C0002    Customer 2  Female   49    Chennai        Gujarat  2023-11-02
2       C0003    Customer 3    Male   40  Ahmedabad        Gujarat  2025-03-07
3       C0004    Customer 4    Male   50    Kolkata    West Bengal  2023-07-04
4       C0005    Customer 5    Male   20    Lucknow          Delhi  2023-02-08

In [44]:
customers.tail()

    customer_id customer_name  gender  age       city        state signup_date
495       C0496  Customer 496    Male   35     Jaipur    Telangana  2024-05-31
496       C0497  Customer 497    Male   55    Lucknow   Tamil Nadu  2024-04-11
497       C0498  Customer 498  Female   52     Mumbai  Maharashtra  2025-02-16
498       C0499  Customer 499    Male   32    Lucknow    Rajasthan  2023-12-11
499       C0500  Customer 500  Female   42  Ahmedabad  Maharashtra  2024-10-03

Q1. Missing city aur state ki exact rows dekho.

In [45]:
customers[customers['city'].isnull()]

  customer_id customer_name gender  age city       state signup_date
7       C0008    Customer 8   Male   59  NaN  Tamil Nadu  2024-05-09

In [46]:
customers[customers['state'].isnull()]

   customer_id customer_name gender  age  city state signup_date
19       C0020   Customer 20   Male   43  Pune   NaN  2025-01-15

Q2. Extra spaces identify karo

In [47]:
customers[customers['customer_name']!=customers['customer_name'].str.strip()]

   customer_id  customer_name  gender  age     city        state signup_date
34       C0035   customer 35   Female   53  Chennai  West Bengal  2023-07-12

In [48]:
customers['customer_name']=customers['customer_name'].str.strip()

Cleaning

In [49]:
customers['city']=customers['city'].fillna("Unknown")
customers['state']=customers['state'].fillna("Unknown")
customers['customer_name']=customers['customer_name'].str.strip()

In [50]:
customers.isnull().sum()

customer_id      0
customer_name    0
gender           0
age              0
city             0
state            0
signup_date      0
dtype: int64

In [51]:
customers[customers["customer_name"] != customers["customer_name"].str.strip()]

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, city, state, signup_date]
Index: []

Products Cleaning

In [52]:
products[products['product_name']!=products['product_name'].str.strip()]

  product_id         product_name     category sub_category  price     cost
4       P005   Bluetooth Speaker   Electronics        Audio   2499  1621.79

In [53]:
for cols in ['product_name','category','sub_category']:
    print(cols,(products[cols]!=products[cols].str.strip()).sum())

product_name 1
category 0
sub_category 0

In [54]:
for cols in ['product_name','category','sub_category']:
    products[cols]=products[cols].str.strip()

In [55]:
products.isnull().sum()

product_id      0
product_name    0
category        0
sub_category    0
price           0
cost            0
dtype: int64

In [56]:
products.duplicated().sum()

np.int64(0)

In [57]:
for cols in ['product_name','category','sub_category']:
    print(cols,(products[cols]!=products[cols].str.strip()).sum())

product_name 0
category 0
sub_category 0

Orders

Q1 — Missing Discount

In [58]:
orders[orders['discount'].isnull()]

,order_id,customer_id,order_date,product_id,quantity,discount,payment_method,region
99,O00100,C0387,2025-08-16,P006,1,NaN,Net Banking,South

Q2 — Payment Method

In [59]:
orders['payment_method'].value_counts()

payment_method
Cash on Delivery    1044
Debit Card          1003
Net Banking         1001
Credit Card          995
UPI                  956
upi                    1
Name: count, dtype: int64

Q3 — Region

In [60]:
orders['region'].value_counts()

region
North    1336
West     1277
East     1202
South    1184
north       1
Name: count, dtype: int64

Orders Cleaning

Missing discount

In [61]:
orders['discount']=orders['discount'].fillna(0)

Payment method standardize

In [62]:
orders["payment_method"] = orders["payment_method"].str.upper()

In [63]:
orders['payment_method'].value_counts()

payment_method
CASH ON DELIVERY    1044
DEBIT CARD          1003
NET BANKING         1001
CREDIT CARD          995
UPI                  957
Name: count, dtype: int64

Region standardize

In [64]:
orders['region']=orders['region'].str.title()

Final Verification

In [65]:
orders.isna().sum()

order_id          0
customer_id       0
order_date        0
product_id        0
quantity          0
discount          0
payment_method    0
region            0
dtype: int64

In [66]:
orders['payment_method'].value_counts()

payment_method
CASH ON DELIVERY    1044
DEBIT CARD          1003
NET BANKING         1001
CREDIT CARD          995
UPI                  957
Name: count, dtype: int64

In [67]:
orders['region'].value_counts()

region
North    1337
West     1277
East     1202
South    1184
Name: count, dtype: int64

Returns

In [68]:
returns.isnull().sum()

return_id        0
order_id         0
return_date      0
return_reason    0
dtype: int64

In [69]:
returns.duplicated().sum()

np.int64(0)

In [70]:
returns["return_id"].duplicated().sum()

np.int64(0)

In [71]:
returns["order_id"].duplicated().sum()

np.int64(0)

In [72]:
returns.dtypes

return_id        str
order_id         str
return_date      str
return_reason    str
dtype: object

In [73]:
returns['return_date']=pd.to_datetime(returns['return_date'])

In [74]:
returns["return_reason"].value_counts()

return_reason
Wrong Product      90
Changed Mind       86
Late Delivery      80
Damaged            76
Product Quality    68
Name: count, dtype: int64

In [75]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="End-to-End",
    user="postgres",
    password="1234",
    port="5432"
)

print("Database connected successfully!")

Database connected successfully!

Customer

In [76]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE customers (
    customer_id VARCHAR(10) PRIMARY KEY,
    customer_name VARCHAR(100),
    gender VARCHAR(20),
    age INT,
    city VARCHAR(50),
    state VARCHAR(50),
    signup_date DATE
);
""")

conn.commit()

print("Customers table created successfully!")

Customers table created successfully!

In [77]:
from psycopg2.extras import execute_values

data = list(customers.itertuples(index=False, name=None))

insert_query = """
INSERT INTO customers
(customer_id, customer_name, gender, age, city, state, signup_date)
VALUES %s
"""

execute_values(cursor, insert_query, data)
conn.commit()

print("Customers data imported successfully!")

Customers data imported successfully!

In [78]:
cursor.execute("SELECT COUNT(*) FROM customers;")

print(cursor.fetchone())

(500,)

Product

In [79]:
cursor.execute("""
CREATE TABLE products (
    product_id VARCHAR(10) PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    price NUMERIC(10,2),
    cost NUMERIC(10,2)
);
""")

conn.commit()

print("Products table created successfully!")

Products table created successfully!

In [80]:
data = list(products.itertuples(index=False, name=None))

insert_query = """
INSERT INTO products
(product_id, product_name, category, sub_category, price, cost)
VALUES %s
"""

execute_values(cursor, insert_query, data)
conn.commit()

print("Products data imported successfully!")

Products data imported successfully!

In [81]:
cursor.execute("SELECT COUNT(*) FROM products;")

print(cursor.fetchone())

(16,)

Orders

In [82]:
cursor.execute("""
CREATE TABLE orders (
    order_id VARCHAR(10) PRIMARY KEY,
    customer_id VARCHAR(10),
    order_date DATE,
    product_id VARCHAR(10),
    quantity INT,
    discount NUMERIC(5,2),
    payment_method VARCHAR(30),
    region VARCHAR(20)
);
""")

conn.commit()

print("Orders table created successfully!")

Orders table created successfully!

In [83]:
data = list(orders.itertuples(index=False, name=None))

insert_query = """
INSERT INTO orders
(order_id, customer_id, order_date, product_id, quantity,
 discount, payment_method, region)
VALUES %s
"""

execute_values(cursor, insert_query, data)
conn.commit()

print("Orders data imported successfully!")

Orders data imported successfully!

In [84]:
cursor.execute("SELECT COUNT(*) FROM orders;")

print(cursor.fetchone())

(5000,)

Return

In [85]:
cursor.execute("""
CREATE TABLE returns (
    return_id VARCHAR(10) PRIMARY KEY,
    order_id VARCHAR(10),
    return_date DATE,
    return_reason VARCHAR(50)
);
""")

conn.commit()

print("Returns table created successfully!")

Returns table created successfully!

In [86]:
data = list(returns.itertuples(index=False, name=None))

insert_query = """
INSERT INTO returns
(return_id, order_id, return_date, return_reason)
VALUES %s
"""

execute_values(cursor, insert_query, data)
conn.commit()

print("Returns data imported successfully!")

Returns data imported successfully!

In [87]:
cursor.execute("SELECT COUNT(*) FROM returns;")

print(cursor.fetchone())

(400,)